In [1]:
!pip install tensorflow

In [2]:
!pip install keras

In [3]:
import keras as k
k.__version__

'2.10.0'

In [4]:
import tensorflow as tf
tf.__version__

'2.10.0'

In [5]:
# Importing
import tensorflow as tf
print(tf.__version__)

2.10.0


In [6]:
# Define tensor constants.
a = tf.constant(2)
b = tf.constant(3)

In [7]:
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

In [8]:
# Access tensors value.
print("add =", add.numpy())
print("sub =", sub.numpy())
print("mul =", mul.numpy())
print("div =", div.numpy())

add = 5
sub = -1
mul = 6
div = 0.6666666666666666


In [9]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[5., 6.], [7., 8.]])

product = tf.matmul(matrix1, matrix2)

In [10]:
# Display Tensor.
product

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [11]:
# Convert Tensor to Numpy.
product.numpy()

array([[19., 22.],
       [43., 50.]], dtype=float32)

In [12]:
t1 = tf.Variable(42) # tensor variable

In [13]:
print(t1)
print(t1.dtype)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>
<dtype: 'int32'>


In [16]:
f1 = tf.Variable(89.)
f1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [17]:
f1.assign(98.)
f1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [18]:
f64 = tf.Variable(89, dtype = tf.float64)
f64.dtype

tf.float64

In [19]:
# The rank (dimensions) of a tensor
t2 = tf.Variable([[[0., 1., 2.], [3., 4., 5.] ], [[6., 7., 8.], [9., 10., 11.]]]) # tensor variable
t2

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [20]:
tf.rank(t2) # dimesion

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [21]:
print(t2.shape) # no of elements, #rows,#columns

(2, 2, 3)


In [22]:
t2[1,1,2] # element no, row, column

<tf.Tensor: shape=(), dtype=float32, numpy=11.0>

In [23]:
t2[1,1,2].numpy()

11.0

In [24]:
t2[0,0,2].numpy()

2.0

In [25]:
# Find the size (total number of elements) of a tensor
s = tf.size(input=t2).numpy()
s

12

In [26]:
# Casting tensor to numpy variable
print(t2.numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [27]:
# Specifying an element of a tensor
print(t2[1, 0, 1].numpy())

7.0
